version : '3'
services: 
    proxy: 
      image: nginx
      ports:
          - "8080:80"
      volumes: 
          - ./default.conf:/etc/conf.d/default.conf
      depends_on:
          - backend
          